spring:
   profiles:
      active:
      - dev  
---
spring: 
   profiles: dev
   application: 
      name: microservicecloud-config-bosi-dev      
---
spring: 
   profiles: test
   application: 
     name: microservicecloud-config-bosi-test
  #请保存为UTF-8格式  
